name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-delay-api
    
    - name: Deploy to Cloud Run
      id: deploy
      run: |
        DEPLOYMENT_URL=$(gcloud run deploy flight-delay-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-delay-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --format="value(status.url)")
        echo "::set-output name=url::$DEPLOYMENT_URL"
    
    - name: Update Makefile with deployment URL
      run: |
        sed -i "s|API_URL=.*|API_URL=${{ steps.deploy.outputs.url }}|" Makefile
    
    - name: Run stress tests against deployed API
      run: make stress-test
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
    
    - name: Run model tests
      run: make model-test
    
    - name: Run API tests
      run: make api-test